<?php
/**
 * Plugin Name: External Repositories
 * Description: Manage external sources for install private plugins and themes.
 * Version: 1.3.1
 * Plugin URI: https://wp-content.io
 * Requires at least: 6.4
 * Requires PHP: 7.1
 * Author: Alexandre Chastan
 * Author URI: https://wp-content.io
 * Text Domain: external-repositories
 * License: GPLv2 or later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Update URI: https://downloads.wp-content.io/
 *
 * Generated by WPC-CLI Generator (https://wp-content.io).
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

require_once __DIR__ . '/updater.php';
require_once __DIR__ . '/src/ExternalRepositoryManager.php';
require_once __DIR__ . '/src/ExternalPluginRepository.php';
require_once __DIR__ . '/src/ExternalThemeRepository.php';
require_once __DIR__ . '/src/ExternalRepository.php';

define( 'EXTERNAL_REPOSITORIES_PLUGIN_DIR_PATH', plugin_dir_path( __FILE__ ) );
define( 'EXTERNAL_REPOSITORIES_PLUGIN_DIR_URL', plugin_dir_url( __FILE__ ) );

function external_repositories_load_domains() {
	// phpcs:ignore PluginCheck.CodeAnalysis.DiscouragedFunctions.load_plugin_textdomainFound -- Not hosted on wordpress.org: translations ship in languages/ and are not loaded just in time by core.
	load_plugin_textdomain( 'external-repositories', false, EXTERNAL_REPOSITORIES_PLUGIN_DIR_PATH . 'languages' );
}

add_action( 'plugins_loaded', 'external_repositories_load_domains' );

function external_repositories_activate() {
	ExternalRepositoryManager::init_db();

	$repositories = ExternalRepositoryManager::get_repositories();

	if ( 0 === count( $repositories ) ) {
		set_transient( 'external_repositories_install_wizard', true, 30 );
	}
}

register_activation_hook( __FILE__, 'external_repositories_activate' );

function external_repositories_plugin_meta( $actions, $plugin_file, $plugin_data, $context ) { // phpcs:ignore Generic.CodeAnalysis.UnusedFunctionParameter.FoundAfterLastUsed -- WordPress filter callback signature.
	$actions['settings'] = sprintf( '<a href="%s">%s</a>', esc_url( ExternalRepositoryManager::get_settings_url() ), __( 'Settings', 'external-repositories' ) );

	return $actions;
}

add_filter( 'network_admin_plugin_action_links_' . plugin_basename( __FILE__ ), 'external_repositories_plugin_meta', 25, 4 );
add_filter( 'plugin_action_links_' . plugin_basename( __FILE__ ), 'external_repositories_plugin_meta', 25, 4 );

function external_repositories_admin_init() {
	if ( get_transient( 'external_repositories_install_wizard' ) ) {
		delete_transient( 'external_repositories_install_wizard' );
		wp_safe_redirect( ExternalRepositoryManager::get_settings_url() );
		exit;
	}
}

add_action( 'admin_init', 'external_repositories_admin_init' );

function external_repositories_admin_enqueue_scripts() {
	global $pagenow;

	switch ( $pagenow ) {
		case 'settings.php':
		case 'options-general.php':
			if ( ExternalRepositoryManager::is_admin_page() ) {
				wp_enqueue_style( 'external-repositories', EXTERNAL_REPOSITORIES_PLUGIN_DIR_URL . 'assets/css/external-repositories.css', '', '1.0.5' );
				wp_enqueue_script( 'external-repositories', EXTERNAL_REPOSITORIES_PLUGIN_DIR_URL . 'assets/js/external-repositories.js', array( 'jquery' ), '1.0.5', true );
			}
			break;

		case 'plugins.php':
			wp_enqueue_script( 'external-repositories-plugins-screen-options', EXTERNAL_REPOSITORIES_PLUGIN_DIR_URL . 'assets/js/plugins-screen-options.js', array( 'jquery' ), '1.1.2', true );
			break;
	}
}

add_action( 'admin_enqueue_scripts', 'external_repositories_admin_enqueue_scripts' );

ExternalRepositoryManager::load();
